name: arcgis_example
description: An example app with the ArcGIS package implementation.

publish_to: none

version: 0.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map_sdk: ^0.8.0

  cupertino_icons: ^1.0.0
  geolocator: ^10.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
