name: arcgis_example
description: An example app with the ArcGIS package implementation.

publish_to: none

version: 0.7.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map
      ref: v0.7.5
  arcgis_map_android:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_android
      ref: v0.7.5
  arcgis_map_ios:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_ios
      ref: v0.7.5
  arcgis_map_method_channel:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_method_channel
      ref: v0.7.5
  arcgis_map_platform_interface:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.5
  arcgis_map_web:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_web
      ref: v0.7.5

  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
