name: arcgis_map
description: Esri ArcGIS map for Flutter for Web, iOS and Android platforms
version: 0.7.6
repository: https://github.com/fluttercommunity/arcgis_map
maintainer: Matthaios Saitakis (@MatthaiosSait), Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou), 
  Pascal Welsch (@passsy), Max Peters (@maxpeters)

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map_ios: ^0.7.5
  arcgis_map_sdk_android: ^0.7.5
  arcgis_map_sdk_platform_interface: ^1.0.0
  arcgis_map_sdk_web: ^0.7.5
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: arcgis_map_sdk_android
      ios:
        default_package: arcgis_map_ios
      web:
        default_package: arcgis_map_sdk_web

topics:
  - map
  - arcgis
