name: arcgis_map
description: Esri ArcGIS Flutter map package.
version: 0.7.3

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_android:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_android
      ref: v0.7.3
  arcgis_map_ios:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_ios
      ref: v0.7.3
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.3
  arcgis_map_method_channel:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_method_channel
      ref: v0.7.3
  arcgis_map_web:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_web
      ref: v0.7.3
  flutter:
    sdk: flutter

# Used to work locally on the package

dev_dependencies:
  flutter_lints: ^2.0.1
