name: arcgis_map
description: Esri ArcGIS Flutter map package.
version: 0.7.0

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_android:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_android
      ref: v0.7.0
  arcgis_map_ios:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_ios
      ref: v0.7.0
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.0
  arcgis_map_method_channel:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_method_channel
      ref: 0.7.0
  arcgis_map_web:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_web
      ref: 0.7.0
  flutter:
    sdk: flutter

# Used to work locally on the package
dependency_overrides:
  arcgis_map_android:
    path: ../arcgis_map_android
  arcgis_map_ios:
    path: ../arcgis_map_ios
  arcgis_map_platform_interface:
    path: ../arcgis_map_platform_interface
  arcgis_map_method_channel:
    path: ../arcgis_map_method_channel
  arcgis_map_web:
    path: ../arcgis_map_web

dev_dependencies:
  flutter_lints: ^2.0.1
