name: arcgis_map
description: Esri ArcGIS Flutter map package.
version: 0.7.5

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_android: ^0.7.5
  arcgis_map_ios: ^0.7.5
  arcgis_map_platform_interface: ^0.7.5
  arcgis_map_method_channel: ^0.7.5
  arcgis_map_web: ^0.7.5
  flutter:
    sdk: flutter

# Used to work locally on the package

dev_dependencies:
  flutter_lints: ^2.0.1
