name: arcgis_map
description: Esri ArcGIS Flutter map package.
version: 0.7.5
repository: https://github.com/fluttercommunity/arcgis_map
maintainer: Matthaios Saitakis (@MatthaiosSait), Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou), 
  Pascal Welsch (@passsy), Max Peters (@maxpeters)

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_android: ^0.7.5
  arcgis_map_ios: ^0.7.5
  arcgis_map_method_channel: ^0.7.5
  arcgis_map_platform_interface: ^0.7.5
  arcgis_map_web: ^0.7.5
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0
