name: arcgis_map_platform_interface
description: Esri ArcGIS Flutter platform interface.
version: 0.7.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.9.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
