name: arcgis_map_platform_interface
description: A common platform interface for the arcgis_map package.
version: 1.0.0
repository: https://github.com/fluttercommunity/arcgis_map
maintainer: Matthaios Saitakis (@MatthaiosSait), Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou), Pascal Welsch (@passsy)

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.9.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  lint: ^2.0.0

flutter:
