name: arcgis_map_platform_interface
description: Esri ArcGIS Flutter platform interface.
version: 0.6.19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.1
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master

flutter:
