name: arcgis_map_android
description: Esri ArcGIS Flutter Android implementation.
version: 0.7.0

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.0
  arcgis_map_method_channel:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_method_channel
      ref: v0.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

# Used to work locally on the package
dependency_overrides:
  arcgis_map_method_channel:
    path: ../arcgis_map_method_channel
  arcgis_map_platform_interface:
    path: ../arcgis_map_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: esri.arcgis.flutter_plugin
        pluginClass: ArcgisMapPlugin
