name: arcgis_map_android
description: Esri ArcGIS Flutter Android implementation.
version: 0.7.5
repository: https://github.com/fluttercommunity/arcgis_map
maintainer: Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou)

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map_method_channel: ^0.7.5
  arcgis_map_platform_interface: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    implements: arcgis_map
    platforms:
      android:
        package: esri.arcgis.flutter_plugin
        pluginClass: ArcgisMapPlugin
        dartPluginClass: AndroidArcgisMapPlugin
