name: arcgis_map_android
description: Esri ArcGIS Flutter Android implementation.
version: 0.7.4

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_platform_interface:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.4
  arcgis_map_method_channel:
    git:
      url: https://github.com/fluttercommunity/arcgis_map.git
      path: arcgis_map_method_channel
      ref: v0.7.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

# Used to work locally on the package

flutter:
  plugin:
    platforms:
      android:
        package: esri.arcgis.flutter_plugin
        pluginClass: ArcgisMapPlugin
