name: arcgis_map_method_channel
description: Esri ArcGIS Flutter method channel implementation.
version: 0.7.3

publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  arcgis_map_platform_interface:
    git:
      url: git@github.com:fluttercommunity/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

# Used to work locally on the package
