name: arcgis_map_ios
description: Esri ArcGIS Flutter iOS implementation.
version: 0.6.19

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  arcgis_map_method_channel:
    path: ../arcgis_map_method_channel
      # todo: replace with repo link
      #git:
      #url: git@github.com:vfdigitalincubator/arcgis_flutter.git
      #path: arcgis_map_method_channel
    #ref: v0.6.19

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.1
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master

# Used to work locally on the package
dependency_overrides:
  arcgis_map_method_channel:
    path: ../arcgis_map_method_channel

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArcgisMapPlugin
