name: arcgis
description: An example app with the ArcGIS package implementation.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.7.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  arcgis_map:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map
      ref: v0.7.1
  arcgis_map_android:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_android
      ref: v0.7.1
  arcgis_map_ios:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_ios
      ref: v0.7.1
  arcgis_map_method_channel:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_method_channel
      ref: v0.7.1
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: v0.7.1
  arcgis_map_web:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_web
      ref: v0.7.1

  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

# Used to work locally on the package


flutter:
  assets:
    - assets/
  uses-material-design: true
