name: arcgis
description: An example app with the ArcGIS package implementation.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  arcgis_map:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map
      ref: main
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: main
  arcgis_map_web:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_web
      ref: main

  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

# Used to work locally on the package
dependency_overrides:
  arcgis_map:
    path: ../../arcgis_map
  arcgis_map_android:
    path: ../../arcgis_map_android
  arcgis_map_ios:
    path: ../../arcgis_map_ios
  arcgis_map_method_channel:
    path: ../../arcgis_map_method_channel
  arcgis_map_platform_interface:
    path: ../../arcgis_map_platform_interface
  arcgis_map_web:
    path: ../../arcgis_map_web


flutter:
  assets:
    - assets/
  uses-material-design: true
