name: arcgis_map_web
description: Esri ArcGIS Flutter web implementation.
version: 0.9.0

publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  arcgis_map_platform_interface:
    git:
      url: git@github.com:phntmxyz/arcgis_map.git
      path: arcgis_map_platform_interface
      ref: main

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  lint: ^1.0.0

# Used to work locally on the package
dependency_overrides:
  arcgis_map_platform_interface:
    path: ../arcgis_map_platform_interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ArcgisMapWeb
        fileName: arcgis_map_web.dart
  assets:
    - assets/arcgis_js_api_custom_build/
    - assets/arcgis_js_api_custom_build/assets/components/assets/date-picker/nls/
    - assets/arcgis_js_api_custom_build/assets/components/assets/icon/
    - assets/arcgis_js_api_custom_build/assets/esri/core/libs/libtess/
    - assets/arcgis_js_api_custom_build/assets/esri/core/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/core/workers/chunks/
    - assets/arcgis_js_api_custom_build/assets/esri/core/workers/
    - assets/arcgis_js_api_custom_build/assets/esri/css/
    - assets/arcgis_js_api_custom_build/assets/esri/geometry/support/
    - assets/arcgis_js_api_custom_build/assets/esri/identity/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/images/basemap/
    - assets/arcgis_js_api_custom_build/assets/esri/images/Legend/
    - assets/arcgis_js_api_custom_build/assets/esri/images/materials/water/
    - assets/arcgis_js_api_custom_build/assets/esri/images/portal/
    - assets/arcgis_js_api_custom_build/assets/esri/images/search/
    - assets/arcgis_js_api_custom_build/assets/esri/images/shared/sliders/
    - assets/arcgis_js_api_custom_build/assets/esri/images/support/
    - assets/arcgis_js_api_custom_build/assets/esri/layers/support/rasterFormats/
    - assets/arcgis_js_api_custom_build/assets/esri/libs/basisu/
    - assets/arcgis_js_api_custom_build/assets/esri/libs/i3s/
    - assets/arcgis_js_api_custom_build/assets/esri/libs/linkchartlayout/
    - assets/arcgis_js_api_custom_build/assets/esri/libs/vxl/
    - assets/arcgis_js_api_custom_build/assets/esri/rest/knowledgeGraph/wasmInterface/
    - assets/arcgis_js_api_custom_build/assets/esri/smartMapping/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/symbols/patterns/
    - assets/arcgis_js_api_custom_build/assets/esri/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/colors/css/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/colors/patterns_json/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/fonts/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/fonts/fonts/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/icons/demo-files/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/icons/fonts/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/icons/readme/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/icons/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/images/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/images/files/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/base/images/maneuvers/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/light/
    - assets/arcgis_js_api_custom_build/assets/esri/themes/dark/
    - assets/arcgis_js_api_custom_build/assets/esri/views/3d/analysis/Slice/images/
    - assets/arcgis_js_api_custom_build/assets/esri/views/3d/environment/resources/
    - assets/arcgis_js_api_custom_build/assets/esri/views/3d/webgl-engine/lib/
    - assets/arcgis_js_api_custom_build/assets/esri/views/interactive/tooltip/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/views/magnifier/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/AreaMeasurement2D/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/AreaMeasurement3D/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Attachments/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Attribution/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/BasemapGallery/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/BasemapLayerList/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/BasemapToggle/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Bookmarks/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/BuildingExplorer/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Compass/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/CoordinateConversion/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Daylight/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Directions/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/DirectLineMeasurement3D/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/DistanceMeasurement2D/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Editor/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/ElevationProfile/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Expand/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Feature/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/FeatureForm/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/FeatureTable/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/FeatureTemplates/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/FloorFilter/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Fullscreen/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Histogram/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/HistogramRangeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Home/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/LayerList/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Legend/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/LineOfSight/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Locate/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Measurement/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/NavigationToggle/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Popup/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Print/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/ScaleBar/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/ScaleRangeSlider/images/scalePreview/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/ScaleRangeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Search/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/ShadowCast/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Sketch/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Slice/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Slider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/ClassedColorSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/ClassedSizeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/ColorSizeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/ColorSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/HeatmapSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/OpacitySlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/smartMapping/SizeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/support/SelectionToolbar/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/support/SnappingControls/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/support/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Swipe/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/TableList/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/TimeSlider/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Track/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/UtilityNetworkTrace/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Weather/t9n/
    - assets/arcgis_js_api_custom_build/assets/esri/widgets/Zoom/t9n/
    - assets/css_overrides/
